run:
  timeout: 5m
  issues-exit-code: 1
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - tparallel
    - errcheck
    - gosimple
