# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - 'release/*'  
  release:
    types: [released]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
          GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
          GEMINI_PRO_API_KEY: ${{ secrets.GEMINI_PRO_API_KEY }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          TESSDATA_PREFIX: "/usr/local/share/tessdata"
