name: Tag and Create Release Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.1.0
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.github_token }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body_path: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false

      # - name: Create ZIP Archive
      #   run: zip -r source_code.zip .

      # - name: Create TAR.GZ Archive
      #   run: tar -czvf source_code.tar.gz .

      # - name: Upload ZIP Archive
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./source_code.zip
      #     asset_name: source_code.zip
      #     asset_content_type: application/zip

      # - name: Upload TAR.GZ Archive
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./source_code.tar.gz
      #     asset_name: source_code.tar.gz
      #     asset_content_type: application/gzip

      # - name: Delete release_notes file
      #   run: rm release_notes.md
